### ISSUE TITLE
JACQ Mirador custom build

### ISSUE THREAD

**Issue by krkabol** [jacq-system/jacq-mirador#2]
My colleagues are mising the download link when using native Mirador (as JACQ does). There is a plugin available (https://github.com/dbmdz/mirador-downloaddialog) providing links to jpeg (Archive Master, or other specific, sadly not).

Repository and ready-to-use build is prepared. Johannes, please review and use if possible at _https://iiif.jacq.org/viewer/_

Petr

**Comment by aragon112358** [comment]
Dear Petr,

thank You for Your contribution. Unfortunately during the last weeks I was very busy, so I didn't have the time to implement it. But now it's finished and is working well, so we have a download-Button in the viewer :-)

Johannes
